const PROFILE_ORDER = ['colony_surface', 'ship_interior', 'derelict_boarding'];

const createProfile = ({
  id,
  label,
  previewLabel,
  previewTitle,
  previewPrompt,
  runtimeHints,
  previewHints,
  allowFly,
  allowJump,
  speed,
  sprintSpeed,
  gravity,
  jumpImpulse,
  mouseSensitivity,
  gamepadLookSensitivity,
  gamepadDeadzone,
}) => ({
  id,
  label,
  previewLabel,
  previewTitle,
  previewPrompt,
  runtimeHints,
  previewHints,
  controls: {
    allowFly,
    allowJump,
    speed,
    sprintSpeed,
    gravity,
    jumpImpulse,
    mouseSensitivity,
    gamepadLookSensitivity,
    gamepadDeadzone,
  },
});

export const traversalProfiles = {
  colony_surface: createProfile({
    id: 'colony_surface',
    label: 'Colony Surface',
    previewLabel: 'Colony Surface Preview',
    previewTitle: 'Surface approach camera',
    previewPrompt: 'Click scene or press A/Start - Deploy team',
    previewHints: [
      'Then: WASD / Mouse / F / Tab',
      'Gamepad: Left stick move, Right stick look, Y fly, A rise/jump',
    ],
    runtimeHints: [
      'WASD - Move',
      'Mouse - Look',
      'Gamepad - Move / Look / A Jump / Y Fly',
      'LClick - Break',
      'RClick - Place',
      '1-9 - Select block',
      'Tab - Inventory',
      'F - Fly mode',
      'Space - Jump/Up',
      'Shift - Sprint/Down',
    ],
    allowFly: true,
    allowJump: true,
    speed: 4.3,
    sprintSpeed: 5.6,
    gravity: -20,
    jumpImpulse: 8,
    mouseSensitivity: 0.002,
    gamepadLookSensitivity: 0.045,
    gamepadDeadzone: 0.18,
  }),
  ship_interior: createProfile({
    id: 'ship_interior',
    label: 'Ship Interior',
    previewLabel: 'Ship Interior Preview',
    previewTitle: 'Ship ingress camera',
    previewPrompt: 'Click scene or press A/Start - Board ship',
    previewHints: [
      'Then: WASD / Mouse / Tab',
      'Gamepad: Left stick move, Right stick look, A interact',
    ],
    runtimeHints: [
      'WASD - Move',
      'Mouse - Look',
      'Gamepad - Move / Look / A Interact',
      'LClick - Use',
      'Tab - Crew / Ship UI',
      'Space - Step / Interact',
      'Shift - Walk slow',
    ],
    allowFly: false,
    allowJump: false,
    speed: 3.6,
    sprintSpeed: 4.6,
    gravity: -20,
    jumpImpulse: 6.4,
    mouseSensitivity: 0.0019,
    gamepadLookSensitivity: 0.038,
    gamepadDeadzone: 0.18,
  }),
  derelict_boarding: createProfile({
    id: 'derelict_boarding',
    label: 'Derelict Boarding',
    previewLabel: 'Derelict Boarding Preview',
    previewTitle: 'Boarding approach camera',
    previewPrompt: 'Click scene or press A/Start - Breach derelict',
    previewHints: [
      'Then: WASD / Mouse / Tab',
      'Gamepad: Left stick move, Right stick look, A interact',
    ],
    runtimeHints: [
      'WASD - Move',
      'Mouse - Look',
      'Gamepad - Move / Look / A Interact',
      'LClick - Scan / Use',
      'Tab - Team / Loot UI',
      'Space - Vault / Interact',
      'Shift - Slow walk',
    ],
    allowFly: false,
    allowJump: false,
    speed: 3.4,
    sprintSpeed: 4.2,
    gravity: -21,
    jumpImpulse: 6.1,
    mouseSensitivity: 0.0019,
    gamepadLookSensitivity: 0.037,
    gamepadDeadzone: 0.18,
  }),
};

export function getTraversalProfile(profileId = 'colony_surface') {
  return traversalProfiles[profileId] || traversalProfiles.colony_surface;
}

export function listTraversalProfiles() {
  return PROFILE_ORDER.map((profileId) => traversalProfiles[profileId]);
}
